# Generated by Django 5.0.2 on 2024-03-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='artist_name',
            field=models.CharField(default='Artist', max_length=100),
        ),
    ]
