# Generated by Django 5.0.2 on 2024-04-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_musicmodel_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='song',
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='playlist_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.playlistmodel')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.musicmodel')),
            ],
        ),
    ]
